<?php
declare(strict_types=1);

// UnixConverter SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

UnixConverterUtility::setRegistrar(function (UnixConverterUtility $u): void {
    $u->clean = [UnixConverterClean::class, 'call'];
    $u->done = [UnixConverterDone::class, 'call'];
    $u->make_error = [UnixConverterMakeError::class, 'call'];
    $u->feature_add = [UnixConverterFeatureAdd::class, 'call'];
    $u->feature_hook = [UnixConverterFeatureHook::class, 'call'];
    $u->feature_init = [UnixConverterFeatureInit::class, 'call'];
    $u->fetcher = [UnixConverterFetcher::class, 'call'];
    $u->make_fetch_def = [UnixConverterMakeFetchDef::class, 'call'];
    $u->make_context = [UnixConverterMakeContext::class, 'call'];
    $u->make_options = [UnixConverterMakeOptions::class, 'call'];
    $u->make_request = [UnixConverterMakeRequest::class, 'call'];
    $u->make_response = [UnixConverterMakeResponse::class, 'call'];
    $u->make_result = [UnixConverterMakeResult::class, 'call'];
    $u->make_point = [UnixConverterMakePoint::class, 'call'];
    $u->make_spec = [UnixConverterMakeSpec::class, 'call'];
    $u->make_url = [UnixConverterMakeUrl::class, 'call'];
    $u->param = [UnixConverterParam::class, 'call'];
    $u->prepare_auth = [UnixConverterPrepareAuth::class, 'call'];
    $u->prepare_body = [UnixConverterPrepareBody::class, 'call'];
    $u->prepare_headers = [UnixConverterPrepareHeaders::class, 'call'];
    $u->prepare_method = [UnixConverterPrepareMethod::class, 'call'];
    $u->prepare_params = [UnixConverterPrepareParams::class, 'call'];
    $u->prepare_path = [UnixConverterPreparePath::class, 'call'];
    $u->prepare_query = [UnixConverterPrepareQuery::class, 'call'];
    $u->graphql_body = [UnixConverterGraphql::class, 'body'];
    $u->graphql_errors = [UnixConverterGraphql::class, 'errors'];
    $u->result_basic = [UnixConverterResultBasic::class, 'call'];
    $u->result_body = [UnixConverterResultBody::class, 'call'];
    $u->result_headers = [UnixConverterResultHeaders::class, 'call'];
    $u->transform_request = [UnixConverterTransformRequest::class, 'call'];
    $u->transform_response = [UnixConverterTransformResponse::class, 'call'];
});
